services:
  wordpress-db:
    container_name: wordpress-db
    platform: linux/x86_64
    image: mysql:8.0.35
    volumes:
      - ./docker/wordpress/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: cdm               # Pour la base de donnée
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # Pour la base de donnée
      MYSQL_USER: ced                   # Pour le site
      MYSQL_PASSWORD: $PWD              # Pour le site
    ports:
      - "3306:3306"

  wordpress:
    platform: linux/x86_64
    container_name: wordpress-site-web
    image: wordpress:latest
    ports:
      - 8000:80
    restart: always
    volumes:
      - ./docker/wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./docker/wordpress/html:/var/www/html
    depends_on:
      - wordpress-db
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: cdm
      WORDPRESS_DB_USER: ced      # Pour le site
      WORDPRESS_DB_PASSWORD: $PWD # Pour le site

  wordpress-pma:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin
    container_name: wordpress-pma
    restart: always
    environment:
      - PMA_HOST=wordpress-db
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    ports:
      - 8001:80
    depends_on:
      - wordpress-db
